version: 2.1

orbs:
  node: circleci/node@5.1.0

executors:
  docker-publisher:
    environment:
      IMAGE_TAG: $DOCKER_HUB_USER_ID/devop-cicd:latest
    docker:
      - image: docker:stable

jobs:
  build:
    working_directory: /devop-cicd
    docker:
      - image: docker:stable
    steps:
      - checkout
      # Set up a separate Docker environment to run `docker` commands in
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            echo "nothing needs to be installed"
      - run:
          name: Build Docker image
          command: |
            docker --version
            docker build -t devop-cicd .
            docker tag devop-cicd $IMAGE_TAG
      - deploy:
          name: Push application Docker image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker push $IMAGE_TAG